<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="ShaharbanuPC" failures="1" tests="1" name="Test new" time="18.863" errors="0" timestamp="2024-12-03T12:10:17 GST">
  <testcase classname="testscript.ManageFooterTextTest" name="ToCheckTheUserIsAbleToUpdateAFooterTextWithInvalidEmailAndPhone" time="6.379">
    <failure type="java.lang.AssertionError" message="The email field and phone filed accept invalid data expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The email field and phone filed accept invalid data expected [false] but found [true]
at testscript.ManageFooterTextTest.ToCheckTheUserIsAbleToUpdateAFooterTextWithInvalidEmailAndPhone(ManageFooterTextTest.java:50)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- ToCheckTheUserIsAbleToUpdateAFooterTextWithInvalidEmailAndPhone -->
  <testcase classname="testscript.ManageFooterTextTest" name="CheckTheUpdateButtonIsDisplayedOnFooterTextPage" time="0.0">
    <ignored/>
  </testcase> <!-- CheckTheUpdateButtonIsDisplayedOnFooterTextPage -->
</testsuite> <!-- Test new -->
